FROM python:alpine
COPY . /appython 

WORKDIR /appython
CMD python proj1.py

#segunda linha vai criar um arquivo chamado appPython
# docker build -t appython . 
# docker run -it appython

# esse programa vai rodar dentro do docker, posso não ter o python instalado esse programa roda 
# no programa python      
#para clonar no repositório dokerhub
#docker tag <nome da imagem(workdir)>:latest <nome  do usuario>/<nome do repositorio>